In [6]:
import torch

In [7]:
filtered_X = torch.load('filtered_X.pt', weights_only=False)
filtered_piece = torch.load('filtered_piece.pt', weights_only=False)
filtered_board = torch.load('filtered_board.pt', weights_only=False)
filtered_Y = torch.load('filtered_Y.pt', weights_only=False)
filtered_mask_t = torch.load('filtered_mask_t.pt', weights_only=False)
filtered_reward = torch.load('filtered_reward.pt', weights_only=False)
X = torch.load('X.pt', weights_only=False)
piece = torch.load('piece.pt', weights_only=False)
board = torch.load('board.pt', weights_only=False)
Y = torch.load('Y.pt', weights_only=False)
mask_t = torch.load('mask_t.pt', weights_only=False)
reward = torch.load('reward.pt', weights_only=False)


In [9]:
epsilon = 1e-8

In [11]:
X.shape

torch.Size([21542, 96])

In [12]:
log_prob = torch.log(X + epsilon)
filtered_log_prob = torch.log(filtered_X + epsilon)

In [26]:
piece[0]

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 

In [31]:
filtered_X[0] - X[0]

tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000, -0.0069,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0002, -0.0022,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000, -0.0378,  0.0490,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000, -0.0608,  0.0585,  0.0000,  0.0000,  0.0000,  0.0000],
       device='cuda:0', grad_fn=<SubBac

In [18]:
reward[0]

tensor([-1.], device='cuda:0')