In [53]:
import torch
import torch.nn as nn

In [56]:
class Torch:
    def __init__(self):
        self.batch_num = 0
        self.layers_dims = [397, 1024, 512, 256, 128, 96] #  5-layer model
        self.learning_rate = 0.001
        checkpoint = False
        self.network = Network(layers_dims)

In [59]:
class Network(nn.Module):
    
    def __init__(self, layers_dims):
        super().__init__()
        layers = []
        for n in range(len(layers_dims) - 2):
            layers.append(nn.Linear(layers_dims[n], layers_dims[n+1]))
            layers.append(nn.ReLU())
        layers.append(nn.Linear(layers_dims[n+1],layers_dims[n+2]))
        layers.append(nn.Softmax())

        self.model = nn.Sequential(*layers)

    def forward(self, x):
        
        return self.model(x)


In [60]:
network = Network(layers_dims)

In [67]:
X = torch.ones(397,50)

In [69]:
network(X.transpose(0,1))

tensor([[0.0113, 0.0096, 0.0099,  ..., 0.0108, 0.0108, 0.0108],
        [0.0113, 0.0096, 0.0099,  ..., 0.0108, 0.0108, 0.0108],
        [0.0113, 0.0096, 0.0099,  ..., 0.0108, 0.0108, 0.0108],
        ...,
        [0.0113, 0.0096, 0.0099,  ..., 0.0108, 0.0108, 0.0108],
        [0.0113, 0.0096, 0.0099,  ..., 0.0108, 0.0108, 0.0108],
        [0.0113, 0.0096, 0.0099,  ..., 0.0108, 0.0108, 0.0108]],
       grad_fn=<SoftmaxBackward0>)

In [22]:
j[0,:] = m[0,:]
j[3,:] = m[3,:]

In [23]:
j

array([[10,  0],
       [ 0,  0],
       [ 0,  0],
       [ 6,  7]])

In [7]:
np.zeros((96))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
z = np.zeros(20)
y = np.zeros(20)
z[0] = 1

In [46]:
if not np.array_equal(y, z):
    print('equal')

equal


In [37]:
z

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [38]:
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [48]:
layers_dims = [397, 1024, 512, 256, 128, 96]

In [52]:
for l in enumerate(layers_dims):
    print(l)