In [1]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import os
import random
import numpy as np


In [2]:
output = torch.rand(10)

In [3]:
output = output.view(2,5)

In [24]:
output

tensor([[0.1989, 0.1976, 0.1971, 0.2037, 0.2027],
        [0.4070, 0.4090, 0.3879, 0.4095, 0.3866]])

In [27]:
output = torch.softmax(output, dim=1)

In [28]:
output

tensor([[0.1998, 0.1995, 0.1994, 0.2007, 0.2005],
        [0.2014, 0.2018, 0.1976, 0.2019, 0.1973]])

In [29]:
weights = torch.tensor([[1],[2]])

In [30]:
output_weighted = output*weights

In [31]:
output_weighted

tensor([[0.1998, 0.1995, 0.1994, 0.2007, 0.2005],
        [0.4028, 0.4036, 0.3952, 0.4038, 0.3947]])

In [7]:
output

tensor([[0.1737, 0.1406, 0.1278, 0.2894, 0.2685],
        [0.2455, 0.2569, 0.1232, 0.2602, 0.1141]])

In [14]:
two_hot = torch.from_numpy(np.array([[0,0,1,1,0],[1,1,1,1,0]]))

In [17]:
output[(two_hot == 1)]

IndexError: index 2 is out of bounds for dimension 0 with size 2